import type { Payment } from "@/lib/supabase";

export const ONE_TIME_PAYMENT_MARKER_PREFIX = "[one_time_payment_id:";
export const ONE_TIME_PAYMENT_MARKER_SUFFIX = "]";

export const buildOneTimePaymentMarker = (id: string) =>
  `${ONE_TIME_PAYMENT_MARKER_PREFIX}${id}${ONE_TIME_PAYMENT_MARKER_SUFFIX}`;

export const isAutoGeneratedOneTimePayment = (
  payment: Pick<Payment, "description">
): boolean => {
  if (!payment.description) {
    return false;
  }

  return payment.description.includes(ONE_TIME_PAYMENT_MARKER_PREFIX);
};